{% set name = "siphon" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/siphon-{{ version }}.tar.gz
  sha256: f99ff44568805d5c00c0599019302a4ea4874d861f00996c8b7de6de4d543f7b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - beautifulsoup4 >=4.9.1
    - numpy >=1.22.0
    - pandas >=1.4.3
    - protobuf >=3.20.0
    - requests >=2.30.0
    - netcdf4 >=1.5.8

test:
  imports:
    - siphon
    - siphon.cdmr
    - siphon.catalog
    - siphon.ncss
    - siphon.radarserver
    - siphon.simplewebservice.wyoming
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Unidata/siphon
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A collection of Python utilities for accessing remote geoscience data
  doc_url: https://unidata.github.io/siphon
  dev_url: https://github.com/Unidata/siphon

extra:
  recipe-maintainers:
    - ocefpaf
    - dopplershift
