{% set name = "siphon" %}
{% set version = "0.7.0" %}
{% set sha256 = "aa4e023113c388fc09d99eef74d1d0985eeffcc1d83ee59c708a56e506b18336" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{name}}-{{version}}.tar.gz
  url: https://pypi.io/packages/source/{{name[0]}}/{{name}}/{{name}}-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - protobuf >=3.0.0a3
    - requests
    - beautifulsoup4
    - pandas
    - netcdf4
    - enum34  # [py27]

test:
  imports:
    - siphon
    - siphon.cdmr
    - siphon.catalog
    - siphon.ncss
    - siphon.radarserver
    - siphon.simplewebservice.wyoming

about:
  home: https://github.com/Unidata/siphon
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A collection of Python utilities for interacting with the Unidata technology stack.'
  doc_url: https://unidata.github.io/siphon
  dev_url: https://github.com/Unidata/siphon

extra:
  recipe-maintainers:
    - ocefpaf
    - dopplershift
