{% set version = "0.8.0" %}

package:
  name: siphon
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/siphon/siphon-{{version}}.tar.gz
  sha256: 1425cc02a82a434ca6b02d9f9c5a2839eecee5ace87de97cac222998b0181af0

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - protobuf >=3.0.0a3
    - requests
    - beautifulsoup4
    - pandas
    - netcdf4
    - enum34  # [py27]

test:
  imports:
    - siphon
    - siphon.cdmr
    - siphon.catalog
    - siphon.ncss
    - siphon.radarserver
    - siphon.simplewebservice.wyoming

about:
  home: https://github.com/Unidata/siphon
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A collection of Python utilities for accessing remote geoscience data'
  doc_url: https://unidata.github.io/siphon
  dev_url: https://github.com/Unidata/siphon

extra:
  recipe-maintainers:
    - ocefpaf
    - dopplershift
