{% set name = "siphon" %}
{% set version = "0.4.1" %}
{% set sha256 = "50a75bfebe411eee758c78acc113e9c7d40a1b07a541985f0eac44385d7bf70b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{name}}-{{version}}.tar.gz
  url: https://pypi.io/packages/source/{{name[0]}}/{{name}}/{{name}}-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - protobuf >=3.0.0a3
    - requests
    - netcdf4
    - enum34  # [py27]

test:
  imports:
    - siphon
    - siphon.cdmr
    - siphon.catalog
    - siphon.ncss
    - siphon.radarserver

about:
  home: https://github.com/Unidata/siphon
  license: MIT
  license_family: MIT
  summary: 'A collection of Python utilities for interacting with the Unidata technology stack.'
  doc_url: https://unidata.github.io/siphon
  dev_url: https://github.com/Unidata/siphon

extra:
  recipe-maintainers:
    - ocefpaf
    - dopplershift
