{% set name = "siphon" %}
{% set version = "0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/siphon-{{ version }}.tar.gz
  sha256: ade3c1f948500085cae619cd6ea75fd5d5e9c9a5377729f09869560588e6999d

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - beautifulsoup4 >=4.6
    - numpy >=1.8
    - pandas
    - protobuf >=3.0.0a3
    - requests >=1.2
    - netcdf4

test:
  imports:
    - siphon
    - siphon.cdmr
    - siphon.catalog
    - siphon.ncss
    - siphon.radarserver
    - siphon.simplewebservice.wyoming
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Unidata/siphon
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A collection of Python utilities for accessing remote geoscience data
  doc_url: https://unidata.github.io/siphon
  dev_url: https://github.com/Unidata/siphon

extra:
  recipe-maintainers:
    - ocefpaf
    - dopplershift
