appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Ho/It0XUUbTyio0txZf4u2piqnueSA/lUvxo2WJl9hY+Jo9AoXFADWn/rxwjuOrMfaIq4RYXgLORRgHBBkrC4EmCGjN1UqB+x5U6XlBcSUKEo6ZWU0TvXNFUZtwGi2tsv3CaJA8QY23RIqJCHZt6iajz42jkxq+5UbGb2ajcSQHYcCqFyJcDTmeEm8e9xQd1wjiRI6O2BT897tYMDB9dzUyBrLS440pLM6WqtAAWgVyatggJ4k6/bx/gmiCtDxz46Mfpp3b90SASDP8DoYthUJOclD7Qp6OXr7am95eI3VFM8B3eEOvREKjaGBGKlPIU68Ji337zqK3+n6d8kLokrsr6JOqWXz/3GoaD5nNP2/t3Uv0tN2o67YuYGcGj7xYFCOTMEXrl2bPl0TMJYyBzSTbNDxhsPYnApJFDJlxm1725LKoGhxiVkgIXjhaQmPFMfJVwmTAcVUg8PpifG9/4f6Jop5+mlTqEjzzy5o82IPDSJWegqyMBZ7b94L92lTRajM4FjA1LdLaS/NDYw8OVvlcXJlysjFeXeKMmSZAQcBu0jUEIdH1K7LIlJcSdYAgfsmGLz9UgP4knyKA/gGYDWrMern3+/Cy8Gt+ASmR3DxdWsK7a7ZiKHRsRJwrUH2jg83I/hP5LgQoBovV/f1d9T3TGnG1DzNvMYrt1HvoHb3Q=}
