travis:
  secure:
    BINSTAR_TOKEN: SK1Y/rSl9xzQt0MtDwk+1FBur7Q+u+d+7KR5CVjIO9WSElSKSnqadwdRNwqcz2qCVTXRmLQE1mvxTmGGedoR+XW4QGqMB2I5VlzRcOuFWwC/+kcU5QVm2xBwDnngFu1TY83p4LiOsGINgj8rLlWnomeqpV1WUOejeVGibES/I6AeUwd+qAz1DagessZlwL4GPCJAZwnxVXFXEWQ6wJyJvRmruxZSXfhf3oMn0Ij9cWREi+aahmS3qfmax56gM70G8uGUPMiURbUjELnBgv00KNWB2fouAzJoBvtmHhh20KhOPYp5SNPdAskp5sNhl4TehrthegAudN6QBBXS78ifvqz/8ajwc3ma2iErbbWL1j0Y775gthK7Tk6Aimu/1ZgOtVZi24G2BqA2SbZsZ/roAD/2IhoMJECQYMuwvXdNoB/R5nBYlkz/7VjSbDL5GDU91sAnBBISfVoDQE/hWZ4+vuGep4+1K9xxkwmuCT3LfBDFC6v2Ev8u2vZBHQYIwvwsEWblqx+5ROueh5/zHoe5IjXd5mIJvmxQlJtUCeJrmXNW+cMhQn1OKT/MsfCt7Aosr10kf7zdEWaXXJxDCxaL41plFQwlvuKwkYAmBnOng9SYyQ5o6zGu1r+SU3ZZ17201sCawLIKFQS/zyG66Wj/3dPbFmWuRgbl1o1P0CeQavU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
